### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by zhizhidory**
Hi Peng-Peng, I'm Dory.
The test url: http://3.114.72.60:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but your font size of 預定行程、登入註冊 are too small.

**Comment by zhizhidory** [comment]
l've already revised it, please check.

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I just noticed that if we scroll down and up quickly, layout will break, and your code will load the same page multiple times.

**Comment by zhizhidory** [comment]
l have added some code, but don't know if it works successfully or not, please help me check.

**Review by cwpeng — APPROVED** [review]
OK. Done.

But always try to figure out clearly what you do and why you do that.

**Pull request merged**
